using System.Collections.Generic;
using UnityEngine;

public class PayoutCalculation : MonoBehaviour
{
  [SerializeField] internal List<int> LineList;
  [SerializeField] private List<GameObject> LineObjetcs;
  [SerializeField] internal List<int> DontDestroyLines = new List<int>();

  //generate lines at runtime accordingly
  internal void GeneratePayoutLinesBackend(int index = -1, bool DestroyFirst = true)
  {

    if (DestroyFirst)
      ResetStaticLine();

    if (index >= 0)
    {
      LineObjetcs[index].SetActive(true);
      print("line object name" + LineObjetcs[index].name);
      return;
    }
    DontDestroyLines.Clear();
  }
  //delete the line generated by button hover
  internal void ResetStaticLine()
  {
    for (int i = 0; i < LineObjetcs.Count; i++)
    {
      if (DontDestroyLines.Contains(i))
        continue;
      else
        LineObjetcs[i].SetActive(false);
    }
  }
}
